---
# - name: "Red Hat 7 | Install Repo files"
#   copy:
#     src: "{{ item }}"
#     dest: /etc/yum.repos.d/
#   loop:
#     - epel7.repo
#     - rhel7_workstation.repo
#     - rhel7_workstation_extras.repo
#     - rhel7_workstation_optional.repo
#     - vscode.repo

- name: "Red Hat 7 | Install Required Yum Package Dependencies"
  yum:
    name:
      - ansible
      - code
      - git
      - nfs-utils
      - python2
      - python2-pip
      - rsync
      - vim
      - yum-utils
    state: present

- name: "Red Hat 7 | Copy Python2 PIP Packages to Remote Host"
  copy:
    src: python2
    dest: /tmp/
    owner: root
    group: root

- name: "Red Hat 7 | Update Python2 PIP Dependencies"
  pip:
    name:
      - "/tmp/python2/setuptools-44.1.1-py2.py3-none-any.whl"
      - "/tmp/python2/pip-20.3.4-py2.py3-none-any.whl"
      - "/tmp/python2/wheel-0.37.1-py2.py3-none-any.whl"
    state: present

- name: "Red Hat 7 | Install Python2 PIP Packages"
  pip:
    name:
      - "/tmp/python2/certifi-2021.10.8-py2.py3-none-any.whl"
      - "/tmp/python2/chardet-4.0.0-py2.py3-none-any.whl"
      - "/tmp/python2/idna-2.10-py2.py3-none-any.whl"
      - "/tmp/python2/ptyprocess-0.7.0-py2.py3-none-any.whl"
      - "/tmp/python2/pexpect-4.8.0-py2.py3-none-any.whl"
      - "/tmp/python2/urllib3-1.26.10-py2.py3-none-any.whl"
      - "/tmp/python2/six-1.16.0-py2.py3-none-any.whl"
      - "/tmp/python2/pyvmomi-7.0.3.tar.gz"
    state: present

- name: "Red Hat 7 | Create Ansible Collection Directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /usr/share/ansible/collections/ansible_collections/ansible
    - /usr/share/ansible/collections/ansible_collections/ansible/posix
    - /usr/share/ansible/collections/ansible_collections/ansible/utils
    - /usr/share/ansible/collections/ansible_collections/community
    - /usr/share/ansible/collections/ansible_collections/community/general
    - /usr/share/ansible/collections/ansible_collections/community/hashi_vault
    - /usr/share/ansible/collections/ansible_collections/community/sops
    - /usr/share/ansible/collections/ansible_collections/community/vmware
    - /usr/share/ansible/collections/ansible_collections/kubernetes/core

- name: "Red Hat 7 | Install Ansible Collections"
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
  loop:
    - { src: ansible-posix-1.4.0.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/ansible/posix/ }
    - { src: ansible-utils-2.6.1.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/ansible/utils/ }
    - { src: community-general-5.3.0.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/community/general/ }
    - { src: community-hashi_vault-3.1.0.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/community/hashi_vault/ }
    - { src: community-sops-1.2.3.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/community/sops/ }
    - { src: community-vmware-2.7.0.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/community/vmware/ }
    - { src: kubernetes-core-2.3.2.tar.gz, dest: /usr/share/ansible/collections/ansible_collections/kubernetes/core/ }

- name: "Red Hat 7 | Remove Python2 PIP Temp Folder"
  file:
    path: python2
    state: absent
